apiVersion: apps/v1
kind: Deployment
metadata:
   name: claud-native-deployment
   labels:
      app: claud-native
spec:
# high availability : 2 pods challenge
    replicas: 2

#selector for pods
    selector:
      matchlabels:
          app: claud-native

# pods template
    template:
      metadata:
        labels:
          app: claud-native
        spec:
          containers:
            - name: claud-native-app
              image: tehzeeb256/claud-native:latest
              imagepullpolicy: Always


              ports:
                - containerport: 8080

# resource limits 
resources:
  limits:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "200m"


# liveness probe (self healing)
livenesssProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

# Readiness probe (traffic routing)
readinessProbe:
  httpGet:
   path: /readiness
   port: 8080
initialDelaySeconds: 3
periodSeconds: 5 