apiVersion: apps/v1
kind: Deployment
metadata:
   name: claud-native-deployment
   labels:
      app: claud-native
spec:
# high availability : 2 pods challenge
    replicas: 2

#selector for pods
    selector:
      matchLabels:
          app: claud-native

# pods template
    template:
      metadata:
        labels:
          app: claud-native
      spec:
          containers:
            - name: claud-native-app
              image: tehzeeb256/claud-native:latest
              imagePullPolicy: Always


              ports:
                - containerPort: 8000

# resource limits 
              resources:
               requests:
                   memory: "64Mi"
                   cpu: "50m"
              limits:
                   memory: "128Mi"
                   cpu: "200m"


# liveness probe (self healing)
              livenessProbe:
               httpGet:
                   path: /healthz
                   port: 8000
              initialDelaySeconds: 5
              periodSeconds: 10

# Readiness probe (traffic routing)
              readinessProbe:
              httpGet:
                   path: /readyz
                   port: 8000
              initialDelaySeconds: 3
              periodSeconds: 5 