apiVersion: v1
kind: Service
metadata:
  name: claud-native-service
  labels:
    app: claud-native

spec: 
# type : nodeport
  type: NodePort
# selector for pods
  selector:
    app: claud-native

# ports configuration
  ports:
    - name: http
      port: 80
      targetport: 8000
      nodeport: 30080
      